### ISSUE TITLE
Asset validation failed 오류

### ISSUE THREAD

**Issue by jinsnet** [nhn/nhncloud.ios.sdk#4]
안녕하세요. 
swift package 로 라이브러리 추가시 앱스토어 올릴때 오류가 발생합니다. 

minimum iOS 버전이 맞지 않는다고 info.plist 를 수정하라고 하는데요. package 로 받은거라 수정이 안됩니다. 

직접 소스를 받아서 info.plist 수정후 프로젝트에 추가하면 잘됩니다.

**Comment by jeffoio** [comment]
xcode 15.3에서 발생합니다 (15.2는 정상 작동)

**Comment by jinsnet** [comment]
Xcode 15.4 에서 수정
